### ISSUE TITLE
Should we have a registry for viewsets?

### ISSUE THREAD

**Issue by RaphaelKimmig** [django-beam/django-beam#8]
This would allow us to auto-generate menus, dashboards and so on.
On the other hand just heaving some tooling to easily add dashboards/menus 
to a template without any magic might be more helpful in longer living projects.

**Comment by RaphaelKimmig** [comment]
After some discussion the rough idea goes like this:

- have a default registry but allow for multiple
- register viewsets via metaclass on class definition
- declare the registry as an attribute on the viewset (but allow for manual registration)

**Comment by HannesWaechter** [comment]
Looks good, 
I would suggest  some unregister function and explain its usage in the "duplicate registration" Exception.
